#! /usr/bin/env bash

sudo yum -y install open-vm-tools nano git wget gcc gcc-c++ java-1.8.0-openjdk java-1.8.0-openjdk-devel
sudo yum -y install zlib zlib-devel 
sudo yum -y install libffi-devel
sudo yum -y install openssl openssl-devel 

sudo yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
sudo subscription-manager repos --enable "rhel-*-optional-rpms" --enable "rhel-*-extras-rpms"

cd /usr/src
wget https://www.python.org/ftp/python/3.7.0/Python-3.7.0.tgz
sudo gunzip Python-3.7.0.tgz && sudo tar -xvf Python-3.7.0.tar

cd Python-3.7.0
./configure --prefix=/usr/local/ --enable-optimizations
sudo make altinstall

sudo ln -s /usr/local/bin/python3.7 /usr/bin/python3

wget https://bootstrap.pypa.io/get-pip.py
python3 get-pip.py
python3 -m pip install --upgrade pip setuptools wheel
python3 -m pip install virtualenv virtualenvwrapper docker-compose
python3 -m pip install docker elasticsearch

pip install docker==2.0.2
pip install requests==2.6.1

sudo yum -y install python-pip
python -m pip install docker

sudo sed -i 's/# include/include/' /etc/nanorc
sudo sed -i "\$aset const" /etc/nanorc

sudo firewall-cmd --permanent --add-port=9200/tcp
sudo firewall-cmd --permanent --add-port=9300/tcp
sudo firewall-cmd --permanent --add-port=5000/tcp
sudo firewall-cmd --permanent --add-port=5601/tcp

sudo wget https://download.docker.com/linux/centos/docker-ce.repo -O /etc/yum.repos.d/docker.repo
sudo yum -y install docker-ce

sudo systemctl start docker
sudo systemctl enable docker

cd /usr/share
sudo git clone https://github.com/elastic/stack-docker.git
cd stack-docker

sudo sed -i 's/6.3.0/6.4.1/' .env
sudo sed -i "\$aPWD=/usr/share/stack-docker" .env
sudo sed -i 's/1.21.2/1.22.0/' setup.yml

make
