#! /usr/bin/env bash

sudo sed -i "\$a192.168.x.x1 kube01" /etc/hosts
sudo sed -i "\$a192.168.x.x2 kube02" /etc/hosts
sudo sed -i "\$a192.168.x.x3 kube03" /etc/hosts
sudo sed -i "\$a192.168.x.x4 kube04" /etc/hosts
sudo sed -i "\$a192.168.x.x5 kube05" /etc/hosts

# Disable swap
sudo swapoff -a
sudo sed -i 's/\/dev\/mapper\/centos-swap/\#\/dev\/mapper\/centos-swap/g' /etc/fstab

# Enable br_netfilter
sudo modprobe br_netfilter
sudo echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables

# Download, install, enable, start Docker, and add scci-admin to the docker group
sudo wget https://download.docker.com/linux/centos/docker-ce.repo -O /etc/yum.repos.d/docker.repo
sudo yum -y install docker-ce
sudo systemctl enable docker
sudo systemctl start docker
sudo usermod -aG docker < username >

# Add the Kubernetes repos and install kubelet, kubeadm, and kubectl
sudo cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF

sudo yum install -y kubelet kubeadm kubectl

# Cgroup changeku
sudo sed -i 's/cgroup-driver=systemd/cgroup-driver=cgroupfs/g' /etc/systemd/system/kubelet.service.d/10-kubeadm.conf

sudo systemctl daemon-reload
sudo systemctl restart kubelet

# Initialize Kubernetes cluster
# https://www.techrepublic.com/article/how-to-install-a-kubernetes-cluster-on-centos-7/
